/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cecar.dominoes2.Cliente.vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.Icon;
import javax.swing.ImageIcon;


public class PanelFichaHorizonta extends javax.swing.JPanel {

    
    String izquierda;
    String derecha;

    public PanelFichaHorizonta(String iz, String de) {
        initComponents();
        this.izquierda=iz;
        this.derecha= de;
        
        lbIzquierda.setSize(70, 75);
        lbDerecha.setSize(70, 75);

        ImageIcon image = new ImageIcon("src/main/java/edu/cecar/dominoes2/Cliente/imagenes/" + iz + ".png");
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(lbIzquierda.getWidth(), lbIzquierda.getHeight(), Image.SCALE_DEFAULT));

        lbIzquierda.setIcon(icon);

        ImageIcon image2 = new ImageIcon("src/main/java/edu/cecar/dominoes2/Cliente/imagenes/" + de + ".png");
        Icon icon2 = new ImageIcon(image2.getImage().getScaledInstance(lbDerecha.getWidth(), lbDerecha.getHeight(), Image.SCALE_DEFAULT));

        lbDerecha.setIcon(icon2);
        
        lbIzquierda.setBorder(BorderFactory.createLineBorder(Color.WHITE, 2, true));
        
        lbIzquierda.revalidate();
        lbIzquierda.repaint();
        
        lbDerecha.revalidate();
        lbDerecha.repaint();
        
    }

    

    @Override
    public String toString() {
        return super.getName(); //To change body of generated methods, choose Tools | Templates.
    }
    
    

    public String getIzquierda() {
        return izquierda;
    }

    public String getDerecha() {
        return derecha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIzquierda = new javax.swing.JLabel();
        lbDerecha = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(150, 80));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        add(Box.createHorizontalGlue());
        add(lbIzquierda);
        add(lbDerecha);
        add(Box.createHorizontalGlue());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbDerecha;
    private javax.swing.JLabel lbIzquierda;
    // End of variables declaration//GEN-END:variables
}
