/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cecar.dominoes2.Cliente.vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class PanelFichaVertical extends javax.swing.JPanel {

    
    String arriba;
    String abajo;
    /**
     * Creates new form panelFicha
     */
    public PanelFichaVertical(String arriba, String abajo) {
        initComponents();
        
        this.arriba= arriba;
        this.abajo= abajo;

        lbArriba.setSize(76, 70);
        lbAbajo.setSize(76, 70);

        ImageIcon image = new ImageIcon("src/main/java/edu/cecar/dominoes2/Cliente/imagenes/" + arriba + ".png");
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(lbArriba.getWidth(), lbArriba.getHeight(), Image.SCALE_DEFAULT));

        lbArriba.setIcon(icon);

        ImageIcon image2 = new ImageIcon("src/main/java/edu/cecar/dominoes2/Cliente/imagenes/" + abajo + ".png");
        Icon icon2 = new ImageIcon(image2.getImage().getScaledInstance(lbAbajo.getWidth(), lbAbajo.getHeight(), Image.SCALE_DEFAULT));

        lbAbajo.setIcon(icon2);
        
        
         lbArriba.setBorder(BorderFactory.createLineBorder(Color.WHITE, 1, true));
        lbAbajo.setBorder(BorderFactory.createLineBorder(Color.WHITE, 1, true));
        
        lbAbajo.revalidate();
        lbArriba.revalidate();
        lbAbajo.repaint();
        lbArriba.repaint();
        
    }

    public String getArriba() {
        return arriba;
    }

    public String getAbajo() {
        return abajo;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbArriba = new javax.swing.JLabel();
        lbAbajo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(80, 150));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        add(Box.createVerticalGlue());
        add(lbArriba);
        add(lbAbajo);
        add(Box.createVerticalGlue());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAbajo;
    private javax.swing.JLabel lbArriba;
    // End of variables declaration//GEN-END:variables
}
